sources:
  - name: venus-etherfi-promo-sepolia
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/51310/venus-etherfi-promo-sepolia/version/latest

documents:
  - '../**/*.graphql'
