name: Tests and Checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"

      - name: Install deps
        # enabeling updating the lock file for a bug in yarn berry likely related to installing github
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn

      - name: Lint
        run: yarn lint

      - name: pretty
        run: yarn pretty
  
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"

      - name: Install deps
        # enabeling updating the lock file for a bug in yarn berry likely related to installing github
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn

      - name: Prepare local
        run: yarn prepare:local

      - name: Codegen
        run: yarn codegen

      - name: Run Matchstick tests
        run: yarn test

  integration-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: docker-compose up -d

      - name: Generate graphql types
        run: |
          docker exec -i subgraph-hardhat-node  yarn workspace isolated-pools-subgraph run create:docker
          docker exec -i subgraph-hardhat-node  yarn workspace isolated-pools-subgraph run deploy:docker
          docker exec -i subgraph-hardhat-node  yarn workspace isolated-pools-subgraph run generate-subgraph-types
      
      - name: Run integration tests
        run: |
          docker exec -i subgraph-hardhat-node yarn workspace isolated-pools-subgraph run test:integration
      
      - name: Stop containers
        if: always()
        run: |
          docker-compose down -v
          docker system prune -f -a --volumes
