name: Tests and Checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Set git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install deps
        # enabeling updating the lock file for a bug in yarn berry likely related to installing github
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn

      - name: Lint
        run: yarn lint

      - name: pretty
        run: yarn pretty
  
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "yarn"

      - name: Set git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install deps
        # enabeling updating the lock file for a bug in yarn berry likely related to installing github
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn

      - name: Prepare local
        run: yarn prepare:local

      - name: Codegen
        run: yarn codegen

      - name: Run Matchstick tests
        run: yarn test
